name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: "0.107.0"
    steps:
      - name: Check version
        if: ${{ github.event.inputs.hugoVersion }}
        run: export HUGO_VERSION="${{ github.event.inputs.hugoVersion }}"
      - name: Install Hugo CLI
        run: sudo snap install hugo
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Update theme
        # (Optional)If you have the theme added as submodule, you can pull it and use the most updated version
        run: git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.107.0"

      - name: Build with hugo
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: tayyabmujahid/tayyabmujahid.github.io
          publish_dir: ./public
          #   keep_files: true
          user_name: tayyabmujahid
          user_email: tayyab.mujahid@gmail.com
          publish_branch: master
        #   cname: example.com
